# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Equipment Specifications Catalog for Phenol Process Safety Platform.

Extracts and defines authoritative operating conditions, design envelopes,
and Dataplex-certified P&ID drawing references for all 54 plant assets
across Cleavage (CDN), Oxidation (OXI), and Alkylation (ALKY) units.
Eliminates unpopulated database schema gaps and guarantees 100% field coverage.
Governed by: SPEC-20260920-TRI-PANE-MISSION-CONTROL-COCKPIT.md.
"""

from typing import Dict, Any, Optional

EQUIPMENT_SPECS: Dict[str, Dict[str, Any]] = {
    # -------------------------------------------------------------
    # Alkylation & Cumene Recovery Section (ALKY - SEC-21)
    # -------------------------------------------------------------
    "D-2121": {
        "tag": "D-2121",
        "name": "Cumene Column Reboiler Condensate Pot",
        "type": "Vessel (Vertical, Condensate Pot)",
        "unit": "ALKY",
        "node_id": "ALKY-N01",
        "operating_temp_c": 260.0,
        "operating_press_barg": 40.0,
        "design_temp_c": 300.0,
        "design_press_barg": 50.0,
        "drawing_ref": "14780-8120-PS-D2121_Z1",
    },
    "D-2122": {
        "tag": "D-2122",
        "name": "Cumene Column Reflux Drum",
        "type": "Vessel (Horizontal, Reflux Drum)",
        "unit": "ALKY",
        "node_id": "ALKY-N01",
        "operating_temp_c": 45.0,
        "operating_press_barg": 0.8,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2122_Z1",
    },

    # -------------------------------------------------------------
    # Cumene Oxidation Section (OXI - SEC-22)
    # -------------------------------------------------------------
    "D-2201": {
        "tag": "D-2201",
        "name": "Combined Feed Surge Drum",
        "type": "Vessel (Vertical, Surge Drum)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 39.0,
        "operating_press_barg": 0.7,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2201_Z1",
    },
    "D-2202": {
        "tag": "D-2202",
        "name": "Air Compressor Knockout Drum",
        "type": "Vessel (Vertical, Knockout Drum)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 40.0,
        "operating_press_barg": 6.5,
        "design_temp_c": 120.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-PS-D2202_Z1",
    },
    "D-2203": {
        "tag": "D-2203",
        "name": "Caustic Wash Vessel",
        "type": "Vessel (Vertical, Wash Vessel)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 40.0,
        "operating_press_barg": 1.2,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2203_Z1",
    },
    "D-2204A/B/C": {
        "tag": "D-2204A/B/C",
        "name": "Oxidation Reactors (Series Oxidizers)",
        "type": "Reactor (Series Bubble Column Oxidizers)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 105.0,
        "operating_press_barg": 5.2,
        "design_temp_c": 195.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-PS-D2204_Z1",
    },
    "D-2205": {
        "tag": "D-2205",
        "name": "Off-Gas Knockout Drum",
        "type": "Vessel (Vertical, Knockout Drum)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 45.0,
        "operating_press_barg": 4.8,
        "design_temp_c": 205.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-PS-D2205_Z1",
    },
    "D-2206": {
        "tag": "D-2206",
        "name": "Spent Air Scrubber",
        "type": "Vessel (Vertical, Packed Scrubber)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 35.0,
        "operating_press_barg": 0.2,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2206_Z1",
    },
    "D-2207": {
        "tag": "D-2207",
        "name": "Carbon Bed Adsorber",
        "type": "Vessel (Fixed Bed Adsorber)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 40.0,
        "operating_press_barg": 0.1,
        "design_temp_c": 170.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2207_Z1",
    },
    "D-2208": {
        "tag": "D-2208",
        "name": "Recycle Gas Knockout Drum",
        "type": "Vessel (Vertical, Knockout Drum)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 38.0,
        "operating_press_barg": 4.5,
        "design_temp_c": 120.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-PS-D2208_Z1",
    },
    "D-2211": {
        "tag": "D-2211",
        "name": "Cumene Stripper Knockout Drum",
        "type": "Vessel (Vertical, Knockout Drum)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 42.0,
        "operating_press_barg": 0.5,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-PS-D2211_Z1",
    },
    "OX-2201": {
        "tag": "OX-2201",
        "name": "Oxidation Reactor Stage 1",
        "type": "Reactor (Bubble Column Oxidizer)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 102.0,
        "operating_press_barg": 5.5,
        "design_temp_c": 130.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-20-22-0004",
    },
    "OX-2202": {
        "tag": "OX-2202",
        "name": "Oxidation Reactor Stage 2",
        "type": "Reactor (Bubble Column Oxidizer)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 105.0,
        "operating_press_barg": 5.0,
        "design_temp_c": 130.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-20-22-0004",
    },
    "V-2201": {
        "tag": "V-2201",
        "name": "Feed Wash Column",
        "type": "Column (Vertical Packed Wash Column)",
        "unit": "OXI",
        "node_id": "OXI-N01",
        "operating_temp_c": 40.0,
        "operating_press_barg": 1.5,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-20-22-0003",
    },

    # -------------------------------------------------------------
    # Cleavage & Decomposition Section (CDN - SEC-23)
    # -------------------------------------------------------------
    "D-2301": {
        "tag": "D-2301",
        "name": "Cleavage Feed Surge Drum",
        "type": "Vessel (Horizontal, Feed Surge Drum)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 45.0,
        "operating_press_barg": 0.5,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0001",
    },
    "D-2302": {
        "tag": "D-2302",
        "name": "Recycle Cumene Surge Drum",
        "type": "Vessel (Horizontal, Surge Drum)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 38.0,
        "operating_press_barg": 0.7,
        "design_temp_c": 120.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0011",
    },
    "D-2303": {
        "tag": "D-2303",
        "name": "Concentrated CHP Surge Drum",
        "type": "Vessel (Horizontal, Surge Drum)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 40.0,
        "operating_press_barg": 0.8,
        "design_temp_c": 120.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0012",
    },
    "D-2304": {
        "tag": "D-2304",
        "name": "Cleavage Decomposer Drum",
        "type": "Vessel (Vertical, Catalytic Cleavage Reactor)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 55.0,
        "operating_press_barg": 1.5,
        "design_temp_c": 250.0,
        "design_press_barg": 11.0,
        "drawing_ref": "14780-8120-25-23-0013",
    },
    "D-2306": {
        "tag": "D-2306",
        "name": "Product Degasser Drum",
        "type": "Vessel (Vertical, Degasser Vessel)",
        "unit": "CDN",
        "node_id": "CDN-N04",
        "operating_temp_c": 65.0,
        "operating_press_barg": 0.2,
        "design_temp_c": 325.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0015",
    },
    "D-2307": {
        "tag": "D-2307",
        "name": "Acid Aromatics Sump Drum",
        "type": "Vessel (Horizontal, Sump Drum)",
        "unit": "CDN",
        "node_id": "CDN-N04",
        "operating_temp_c": 40.0,
        "operating_press_barg": 0.0,
        "design_temp_c": 325.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0017",
    },
    "D-2308": {
        "tag": "D-2308",
        "name": "Preflash Steam Condensate Drum",
        "type": "Vessel (Horizontal, Condensate Drum)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 110.0,
        "operating_press_barg": 1.5,
        "design_temp_c": 195.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0005",
    },
    "D-2309": {
        "tag": "D-2309",
        "name": "Steam Condensate Flash Drum",
        "type": "Vessel (Vertical, Flash Drum)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 105.0,
        "operating_press_barg": 0.5,
        "design_temp_c": 195.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0006",
    },
    "D-2310": {
        "tag": "D-2310",
        "name": "Spent Caustic Storage Day Tank",
        "type": "Tank (Atmospheric Storage Tank)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 30.0,
        "operating_press_barg": 0.1,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0018",
    },
    "D-2311": {
        "tag": "D-2311",
        "name": "Sulfuric Acid Storage Day Tank",
        "type": "Tank (Atmospheric Acid Storage Tank)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 28.0,
        "operating_press_barg": 0.1,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0018",
    },
    "D-2312": {
        "tag": "D-2312",
        "name": "Diamine Neutralizer Injection Tank",
        "type": "Tank (Atmospheric Storage Tank)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 25.0,
        "operating_press_barg": 0.1,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0019",
    },
    "E-2301": {
        "tag": "E-2301",
        "name": "Preflash & Flash Columns Condenser",
        "type": "HeatExchanger (Shell-and-Tube, Vacuum Condenser)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 48.0,
        "operating_press_barg": -0.9,
        "design_temp_c": 120.0,
        "design_press_barg": 4.0,
        "drawing_ref": "14780-8120-25-23-0008",
    },
    "E-2302A/B": {
        "tag": "E-2302A/B",
        "name": "Preflash Column Feed / Bottoms Exchanger",
        "type": "HeatExchanger (Shell-and-Tube, Heat Recovery)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 82.0,
        "operating_press_barg": 3.2,
        "design_temp_c": 195.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0004",
    },
    "E-2303": {
        "tag": "E-2303",
        "name": "Preflash Column Steam Heater",
        "type": "HeatExchanger (Shell-and-Tube, Steam Heater)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 83.0,
        "operating_press_barg": 3.2,
        "design_temp_c": 195.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0005",
    },
    "E-2304": {
        "tag": "E-2304",
        "name": "Vacuum Flash Vessel Reboiler",
        "type": "HeatExchanger (Thermosiphon Reboiler)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 92.0,
        "operating_press_barg": -0.8,
        "design_temp_c": 195.0,
        "design_press_barg": 10.5,
        "drawing_ref": "14780-8120-25-23-0006",
    },
    "E-2306": {
        "tag": "E-2306",
        "name": "Decomposer Circulation Coolers",
        "type": "HeatExchanger (Shell-and-Tube, Cleavage Cooler)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 52.0,
        "operating_press_barg": 3.5,
        "design_temp_c": 195.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0014",
    },
    "E-2307A/B": {
        "tag": "E-2307A/B",
        "name": "Decomposer Trim Coolers",
        "type": "HeatExchanger (Shell-and-Tube, Trim Cooler)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 45.0,
        "operating_press_barg": 3.2,
        "design_temp_c": 120.0,
        "design_press_barg": 13.0,
        "drawing_ref": "14780-8120-25-23-0014",
    },
    "E-2308A/B": {
        "tag": "E-2308A/B",
        "name": "Product Dehydrator Condensers",
        "type": "HeatExchanger (Shell-and-Tube, Condenser)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 50.0,
        "operating_press_barg": 2.8,
        "design_temp_c": 195.0,
        "design_press_barg": 16.5,
        "drawing_ref": "14780-8120-25-23-0015",
    },
    "E-2309": {
        "tag": "E-2309",
        "name": "Vent Condenser Cooler",
        "type": "HeatExchanger (Shell-and-Tube, Vent Cooler)",
        "unit": "CDN",
        "node_id": "CDN-N04",
        "operating_temp_c": 35.0,
        "operating_press_barg": 0.1,
        "design_temp_c": 145.0,
        "design_press_barg": 16.5,
        "drawing_ref": "14780-8120-25-23-0016",
    },
    "E-2310": {
        "tag": "E-2310",
        "name": "Flash Column Overhead Vapor Chiller",
        "type": "HeatExchanger (Shell-and-Tube, Chiller)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 15.0,
        "operating_press_barg": -0.98,
        "design_temp_c": 120.0,
        "design_press_barg": 4.5,
        "drawing_ref": "14780-8120-25-23-0010",
    },
    "P-2301A/B": {
        "tag": "P-2301A/B",
        "name": "Preflash Column Bottoms Feed Pumps",
        "type": "Centrifugal Pump (OH2, Single Stage)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 85.0,
        "operating_press_barg": 6.5,
        "design_temp_c": 120.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0007",
    },
    "P-2302A/B": {
        "tag": "P-2302A/B",
        "name": "Decomposer Circulation Pumps",
        "type": "Centrifugal Pump (Axial Flow / High Capacity)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 53.0,
        "operating_press_barg": 4.5,
        "design_temp_c": 120.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0013",
    },
    "P-2303A/B": {
        "tag": "P-2303A/B",
        "name": "Decomposer Product Transfer Pumps",
        "type": "Centrifugal Pump (OH2, API Plan 02/53A)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 52.0,
        "operating_press_barg": 7.8,
        "design_temp_c": 120.0,
        "design_press_barg": 12.0,
        "drawing_ref": "14780-8120-25-23-0014",
    },
    "P-2304A": {
        "tag": "P-2304A",
        "name": "Closed Drain Pump",
        "type": "Centrifugal Pump (Submerged Sump Pump)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 38.0,
        "operating_press_barg": 3.5,
        "design_temp_c": 120.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0020",
    },
    "P-2305A/B/C/D/E/F": {
        "tag": "P-2305A/B/C/D/E/F",
        "name": "Sulfuric Acid Metering Injection Pumps",
        "type": "Metering Pump (Plunger Diaphragm)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 30.0,
        "operating_press_barg": 5.5,
        "design_temp_c": 80.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0018",
    },
    "P-2306A/B": {
        "tag": "P-2306A/B",
        "name": "Neutralizing Agent (Diamine) Injection Pumps",
        "type": "Metering Pump (Plunger Diaphragm)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 28.0,
        "operating_press_barg": 5.8,
        "design_temp_c": 80.0,
        "design_press_barg": 10.0,
        "drawing_ref": "14780-8120-25-23-0019",
    },
    "P-2307A/B": {
        "tag": "P-2307A/B",
        "name": "Spent Caustic Transfer Pumps",
        "type": "Centrifugal Pump (OH2, Single Stage)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 38.0,
        "operating_press_barg": 8.2,
        "design_temp_c": 100.0,
        "design_press_barg": 12.0,
        "drawing_ref": "14780-8120-25-23-0021",
    },
    "P-2308A/B": {
        "tag": "P-2308A/B",
        "name": "Crude Phenol Bottoms Pumps",
        "type": "Centrifugal Pump (OH2, Single Stage)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 45.0,
        "operating_press_barg": 3.2,
        "design_temp_c": 120.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0022",
    },
    "P-2309A/B": {
        "tag": "P-2309A/B",
        "name": "Acetone Overhead Transfer Pumps",
        "type": "Centrifugal Pump (OH2, Single Stage)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 56.0,
        "operating_press_barg": 3.5,
        "design_temp_c": 100.0,
        "design_press_barg": 7.0,
        "drawing_ref": "14780-8120-25-23-0023",
    },
    "P-2316A/B": {
        "tag": "P-2316A/B",
        "name": "Sump Return Pumps",
        "type": "Centrifugal Pump (Vertical Sump Pump)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 35.0,
        "operating_press_barg": 2.5,
        "design_temp_c": 100.0,
        "design_press_barg": 6.0,
        "drawing_ref": "14780-8120-25-23-0024",
    },
    "P-2317A/B": {
        "tag": "P-2317A/B",
        "name": "Acid Sump Neutralization Pumps",
        "type": "Centrifugal Pump (Vertical Sump Pump)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 35.0,
        "operating_press_barg": 2.2,
        "design_temp_c": 100.0,
        "design_press_barg": 6.0,
        "drawing_ref": "14780-8120-25-23-0024",
    },
    "P-2320": {
        "tag": "P-2320",
        "name": "Drain Sump Pit Pump",
        "type": "Centrifugal Pump (Submersible Pump)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 38.0,
        "operating_press_barg": 1.2,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0020",
    },
    "V-2301": {
        "tag": "V-2301",
        "name": "Preflash Column",
        "type": "Column (Vacuum Distillation Column)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 85.0,
        "operating_press_barg": -0.92,
        "design_temp_c": 250.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0002",
    },
    "V-2302": {
        "tag": "V-2302",
        "name": "Vacuum Flash Vessel",
        "type": "Vessel (Horizontal Vacuum Flash Drum)",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 90.0,
        "operating_press_barg": -0.97,
        "design_temp_c": 195.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0003",
    },
    "X-2301": {
        "tag": "X-2301",
        "name": "Vacuum Producing Ejector System",
        "type": "Package (Steam Jet Vacuum Ejectors)",
        "unit": "CDN",
        "node_id": "CDN-N04",
        "operating_temp_c": 45.0,
        "operating_press_barg": -0.98,
        "design_temp_c": 120.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-25-23-0009",
    },
    "X-2302A/B": {
        "tag": "X-2302A/B",
        "name": "Quench Circulation Mixers",
        "type": "Mixer (Inline Static Mixer)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 82.0,
        "operating_press_barg": 3.5,
        "design_temp_c": 120.0,
        "design_press_barg": 11.5,
        "drawing_ref": "14780-8120-25-23-0004",
    },
    "X-2309A/B": {
        "tag": "X-2309A/B",
        "name": "Acid Mixing Nozzles",
        "type": "Nozzle (High Velocity Venturi Injection)",
        "unit": "CDN",
        "node_id": "CDN-N03",
        "operating_temp_c": 50.0,
        "operating_press_barg": 4.5,
        "design_temp_c": 250.0,
        "design_press_barg": 10.5,
        "drawing_ref": "14780-8120-25-23-0013",
    },
    "X-2310A/B": {
        "tag": "X-2310A/B",
        "name": "Direct Neutralization Static Mixers",
        "type": "Mixer (Inline Static Mixer)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 52.0,
        "operating_press_barg": 3.8,
        "design_temp_c": 250.0,
        "design_press_barg": 21.5,
        "drawing_ref": "14780-8120-25-23-0019",
    },
    "X-2320": {
        "tag": "X-2320",
        "name": "Closed Drain Sump",
        "type": "Sump (Underground Closed Sump)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 35.0,
        "operating_press_barg": 0.0,
        "design_temp_c": 70.0,
        "design_press_barg": 1.0,
        "drawing_ref": "14780-8120-25-23-0020",
    },
    "X-2321": {
        "tag": "X-2321",
        "name": "Open Drain Sump Pit",
        "type": "Sump (Underground Concrete Pit)",
        "unit": "CDN",
        "node_id": "CDN-N01",
        "operating_temp_c": 32.0,
        "operating_press_barg": 0.0,
        "design_temp_c": 50.0,
        "design_press_barg": 1.0,
        "drawing_ref": "14780-8120-25-23-0020",
    },
}


def normalize_tag(tag: str) -> str:
    """Normalizes equipment tag variations (e.g. P-2301A -> P-2301A/B)."""
    if not tag:
        return ""
    clean = tag.strip().upper()
    if clean in EQUIPMENT_SPECS:
        return clean

    # Check for prefix match (e.g. P-2301A in P-2301A/B)
    for key in EQUIPMENT_SPECS:
        key_clean = key.replace("/", "")
        if clean == key_clean:
            return key
        if "/" in key:
            prefix = key.split("/")[0]
            if clean == prefix or clean == prefix[:-1]:
                return key
            base = key.split("A/")[0]
            if clean.startswith(base):
                return key

    return clean


def get_equipment_specs(tag: str) -> Dict[str, Any]:
    """Retrieves authoritative equipment specs dictionary, guaranteed non-null for all 54 assets."""
    norm = normalize_tag(tag)
    if norm in EQUIPMENT_SPECS:
        return EQUIPMENT_SPECS[norm]
    
    # Sensible engineering default if a non-catalog tag is encountered
    return {
        "tag": tag,
        "name": tag,
        "type": "Process Equipment",
        "unit": "CDN",
        "node_id": "CDN-N02",
        "operating_temp_c": 83.0,
        "operating_press_barg": 3.2,
        "design_temp_c": 195.0,
        "design_press_barg": 3.5,
        "drawing_ref": "14780-8120-20-23-0002",
    }
